name: publish
description: Publish package on "release=<version>" in commit message.

runs:
    using: "composite"
    steps:
      - run: |
        commit_message=$(git log -1 --pretty=%B)
        release_value=$(echo "$commit_message" |  sed -n 's/.*release=\([^[:space:]]*\).*/\1/p')
        if [ -n "$release_value" ]; then
         npm version $release_value
         npm publish
        fi
