name: publish
description: Publish package on "release=<version>" in commit message.
inputs:
  artifact:
    type: string
    required: true
  email:
    type: string
    default: "dev@example.com"
    required: false

runs:
    using: "composite"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - run: |
          commit_message=$(git log -1 --pretty=%B)
          release_value=$(echo "$commit_message" |  sed -n 's/.*release=\([^[:space:]]*\).*/\1/p')
          if [ -n "$release_value" ]; then
            git config --global user.email ${{ inputs.email }}
            git config --global user.name ${{ github.actor }}
            npm version $release_value
            npm publish --access public
          else
            echo "No release detected..."
          fi
        shell: bash


