name: auto-pr
description: Create a pull request from the current branch.
inputs:
  base:
    type: string
    default: "master"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: |
          branch=$(git branch --show-current)
          title=$(git log -1 --format=%s HEAD)
          body=$(git log -1 --format=%B HEAD)
          set +e
          gh pr create --title "$title" --body "$body" --base ${{inputs.base}} --head "$branch"
          set -e
      shell: bash
