name: auto-pr
description: Create a pull request from the current branch
inputs:
  base:
    type: string
    default: "master"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: |
          BRANCH=$(git branch --show-current)
          TITLE=$(git log -1 --format=%s HEAD)
          BODY=$(git log -1 --format=%B HEAD)
          gh pr create --title "$TITLE" --body "$BODY" --base ${{inputs.base}} --head "$BRANCH"
      shell: bash
