name: auto-pr
description: Create a pull request from the current branch

runs:
  using: "composite"
  steps:
    - run: |
          BRANCH=$(git branch --show-current)
          TITLE=$(git log -1 --format=%s HEAD)
          BODY=$(git log -1 --format=%B HEAD)
          PAYLOAD="{\"title\":\"$TITLE\",\"head\":\"$BRANCH\",\"body\":\"$BODY\",\"base\":\"master\"}"
          RESPONSE=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d "$PAYLOAD" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/pulls)

          PR_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Pull request created: $PR_URL"
